export enum MutualFundInvestmentMethod {
  LUMP_SUM_INVESTMENT = "LUMP_SUM_INVESTMENT",
  SYSTEMATIC_INVESTMENT_PLAN = "SYSTEMATIC_INVESTMENT_PLAN",
  SYSTEMATIC_WITHDRAWAL_PLAN = "SYSTEMATIC_WITHDRAWAL_PLAN",
}
